version: "3.8"

services:
  server:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php-laravel
      - mysql
  php-laravel:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    

  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
    volumes:
      - db:/var/lib/mysql:rw
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
volumes:
  db:
    driver: local