version: "3.8"

services:
  server-nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php-laravel:
    build:
      context: ./dockerfile
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
    volumes:
      - mysqldb:/var/lib/mysql:rw
  composer:
    build: 
      context: ./dockerfile
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
